### ISSUE TITLE
Ability to implicitly load services without configuration

### ISSUE THREAD

**Issue by ljacomet** [Terracotta-OSS/terracotta-apis#109]
The idea is to be able to start services without specifying any configuration in the server config file.

This is triggered by Ehcache development that will end up having to build some supporting services to be used by the various entities involved in making clustering work. And as these services are more of an internal concern of Ehcache as a platform citizen and not a user facing thing, they should remain _invisible_.

**Comment by jd0-sag** [comment]
To proceed with this, we will need to make some small changes to how ServiceProvider instances are loaded.  Currently, they are found via the class exposed by ServiceProviderConfiguration.getServiceProviderType().

Those provider configurations are also not the immediate load point since they are actually parsed from the config, by ServiceConfigParser implementations.

ServiceConfigParser instances are found via the ServiceLocator, called from the TCServerMain.

Hence, the difficulty will come in how we address those additional levels of indirection.  I suppose that is the question of whether we bypass them, creating a new load path, or if we change how these are used by the config parser to allow them to match on "nothing" to instantiate the service provider.

**Comment by myronkscott** [comment]
My initial instinct would be to bypass and create yet another load type with it's own set of rules.

**Comment by myronkscott** [comment]
We will also add the ability to add permanent entities via annotation.

**Comment by myronkscott** [comment]
Implicit services will be added via the normal ServiceLocator mechanism just without configuration.  On startup the server will look for org.terracotta.entity.ServiceProvider implementations.
