### ISSUE TITLE
Javadoc the thread safety guarantees expected from ServiceProvider implementers

### ISSUE THREAD

**Issue by albinsuresh** [Terracotta-OSS/terracotta-apis#131]
The thread safety guarantees expected from the implementer of `ServiceProvider` interface need to be javadoc'ed. Especially for the _getService()_ method.

**Comment by jd0-sag** [comment]
What are you trying to do which opens the question?

The other methods in the interface are documented as to when they are called, since they are either read-only (`getProvidedServiceTypes()`) or related to the service life-cycle (`initialize()` and `clear()`).

`getService()` can be called, concurrently, by every thread in the system (either running within the same entity or running in different entities - passing in different `consumerID` values), since the layer between the entity and the service is very thin (and really just exists to inject the `consumerID`).  Typically, however, the entity will just call `getService()` when it is first instantiated and will cache the result.  Even in that case, multiple entities could be created at the same time.

We can document this but I want to understand more about why you are asking and what guarantees you would expect to see required.

**Comment by albinsuresh** [comment]
The question arose when I was trying to implement a service on my own. As you pointed out I was expecting that the other methods(since part of the life-cycle or serving read only content) would only be called by a single thread. But I was not clear on whether or not to make _getService()_ method thread-safe. Multiple entities could concurrently request this service but through the `ServiceRegistry` and not the _getService()_ method on the `ServiceProvider`. If it was the latter case I would have made it thread-safe. But since it is the former, I was confused. Because the link between `ServiceRegistry.getService()` and `ServiceProvider.getService()` was not clear from the API doc which raised this question on whether or not to make it thread safe and what the expectation is from the platform side as it is the platform that invokes this method and not the consumer entities directly.

**Comment by jd0-sag** [comment]
It depends on what you mean by "thread safe" in this context.  It can be called, concurrently, on multiple threads.  Nothing prevents that.

I suppose I am somewhat confused as to what you are doing in the implementation where it would matter.  Typically, the implementation just instantiates a service instance and returns that, while these service instances can each be called concurrently on whatever interfaces they expose (this is typically the more interesting/complex case).

If you are doing something to intern the instances, for example, you will need to synchronize within the provider.

**Comment by albinsuresh** [comment]
There is some caching involved in my implementation. So for one _consumerID_ I'm creating the service instance and caching it so that the requests from the same "consumer" gets the same instance(Relying on this behavior when passive entity becomes active and requests for the service instance created by the passive).
So when caching is involved I'll have code blocks like:

```java
if(not present in cache)
  create an instance and put it in the cache
return cached-entry
```

That piece of code is not thread safe. So I was wondering if I should have made it thread-safe? Since there was nothing explicitly in the javadoc I assumed that I should it make it thread safe and did that anyway. And felt that making the expectation explicit would have helped.
