### ISSUE TITLE
Add a best-efforts "event push" method to IMonitoringProducer

### ISSUE THREAD

**Issue by jd0-sag** [Terracotta-OSS/terracotta-apis#134]
The methods in `IMonitoringProducer` are effective when it comes to communicating opaque data in a "high-fidelity" way:  an implementation of the interface can keep the data set to a well-defined size even as events mutate it, due to the tree structure.

We need a way to communicate "low-fidelity" data, though.  This includes things like statistics or frequent state notifications which we would like to communicate but can be safely dropped without any impact on correctness.

The suggested interface is:
`
public void pushBestEffortsData(String[] path, Object data);
`

The underlying implementation is free to drop these messages in the cases where they are arriving more quickly than they can be consumed by some underlying process.  The implementation decides both how much data it will try to hold, before dropping, as well as the dropping strategy ("oldest", "most similar", or "most recent", for example).

**Comment by jd0-sag** [comment]
@mathieucarbou @anthonydahanne @myronkscott @ramsai1729: Let me know what you think.

**Comment by mathieucarbou** [comment]
this is perfect for me :-)

**Comment by mathieucarbou** [comment]
@jd0-sag : @anthonydahanne : 3 remarks / questions:

__QUESTION 1:__

Also, will you add something like 

`public void pushHighFidelity(String[] path, Object data);`

or not yet ?
For data that must be pushed in the tree, but also be kept in case of a failover, so replicated.

__QUESTION 2:__

Naming: I would prefer the simple names I think such as:

- `enqueue(path, data)`: to put a "persistent" data in a queue that will be replicated
- `offer(path, data)` or `push(path, data)`: to just make some other component "aware" of a new "transient" data that would only live in memory in the active

=> 2 methods for the 2 use case dependently of the importance of the data

__QUESTION 3:__

When the `pushBestEffortsData()` (or `offer` / `push`) is called, then there is 2 options:

1. put the data in a common data structure in the tree, which will be common across all consumers.
=> So when a consumer "polls", it removes the value and other consumers won't read it

2. put the data in all consumer trees. All consumers could have their own transient tree copy, maintaining their own queue / ring buffer. 
=> So a poll of a pushed value won't impact other consumers.

For the moment, for what we need, there is no difference between the 2 implementations. But I wonder if there could be some "normal" use cases of several entities reading the same path from the tree...

**Comment by jd0-sag** [comment]
We still need to figure out if there is any tree data which _isn't_ replicated.  I suspect that the entire tree will always be replicated (since passive data is otherwise inaccessible).  This is still something we need to determine as we currently treat it as having "special" branches which are replicated into specific places on the replicated copies.

I currently think that everything will be replicated, subject to the reliability of its API:  tree mutations will always be replicated while "BestEfforts" data will be replicated if the interconnect isn't saturated.  Just how aggressively this is detected is up to the API (meaning that we will probably start with a static heuristic along the lines of "replicate every 10th best efforts message", or something).

The details of how the consumer works is completely up to the implementation of this interface and how its consumer interface works.  It isn't really something that the component producing the data should worry about (otherwise, it has to understand and worry about that implementation and what it means to have multiple consumers and how/if they have independent states).

**Comment by mathieucarbou** [comment]
Agree with that!

I think that if everything *can* be replicated, it would simplify the API and consumers won't need to know some specifics. So it is the best.

So it also means that the tree (and the associated queues or ring buffers) needs to be __common__ across all consumers, and a consumer that would consume the statistics, notification or op. events would then prevent other consumers from seeing the consumed value.

If you find this acceptable as a contract for the consumer API, then I'll go with that.

**Comment by jd0-sag** [comment]
2 concerns with that:

1. I am not sure if we want to describe "parent" and "nodeName" since there isn't really a "structure", so much as just a named path.  Otherwise, we would need it to be directly associated with the tree which could cause problems if these got somehow out of sync (since they have different constraints), meaning that a relative ordering rule would need to be imposed.  Ultimately, the only reason why I suggested a "path" instead of a "name" is because they are generally expected to be a quasi-structured collection of keys (although the idea of just using a `String name` may be simpler and externally equivalent.
1. It isn't possible, in general, to return whether or not the data was "inserted" since it the information will likely be lazily transmitted when the next opportunity presents itself.  Additionally, I don't expect that the caller would be able to use this information in any meaningful way.

**Comment by mathieucarbou** [comment]
For 1, I do not see the reason why we should not associate the tree with it ?

Concrete example is client-side notifications, going through the management entity. If it is not there (management root), then the push() would return false. Like addNode does.

If the management root gets removed, then all the data under this tree, plus all underlying "queue" structures are discarded.

What I mean is that our need is to be able to push and read several data specifically into some tree's leaf.

If also I call push({"platform", "servers"}, "a-key", my-object), then I am expected that the method returns false because there is no "buffer" associated to this key.

For 2, I do not see the difference between addNode, removeNode and push(). We said that ALL the methods will get replicated. So it means that everything is equally important. So the argument also applies to addNode / removeNode methods.

**Comment by mathieucarbou** [comment]
Here is what we do currently:

```
    //TODO: MATHIEU - PERF: https://github.com/Terracotta-OSS/terracotta-platform/issues/108
    // this will be the paths where the client-side stats and notifications are
    if (!consumer.getChildNamesForNode(array("management", "notifications")).isPresent()) {
      producer.addNode(array("management"), "notifications", new LinkedBlockingQueue<>(config.getMaximumUnreadClientNotifications()));
    }
    if (!consumer.getChildNamesForNode(array("management", "statistics")).isPresent()) {
      producer.addNode(array("management"), "statistics", new LinkedBlockingQueue(config.getMaximumUnreadClientStatistics()));
    }
```

**Comment by jd0-sag** [comment]
There are a few concerns with direct interactions with the broader tree.  One of those is how to rationalize the case of trying to add a node and push data associated with the same node and path:  which one "happens" (and does that answer change if you try to call it again)?  I generally have concerns of the raciness of some of these interactions, as well.  If we force them into different name-spaces, that problem becomes far more constrained.

The idea that the tree shape could be used to selectively "mute" some kinds of data is kind of interesting, I suppose.  It seems as though there would always be a more reliable way to know this, though, or the producer just shouldn't care.

If you need to know both the consumer and producer interface, in anything other than the TMS entity, I suspect that this usage is incorrect.  The entire reason to keep those distinct is that the consumer is really just a way of permitting arbitrarily tight coupling between the monitoring service implementation and its corresponding TMS entity while ensuring that nothing else needs to know the details of its implementation.  I don't know why you are needing both in this case.  It makes me think that there is something wrong.

**Comment by jd0-sag** [comment]
In the name of keeping things simple, we can probably go one step further than the initial proposal, and do away with the use of a "path" in favor of just a "name" (which the users can internally formalize/namespace as they see fit).  The main reason for the tree structure, initially, was so that a blind implementation can represent an infinite stream of events as a finite data structure, so long as it has finite meaning.  Given that these events aren't required to be fully cached (only best efforts), we can make a far simpler interface with fewer usage rules.

The implementation is free to limit how many data elements it caches, potentially on a per-key or global level, subject to the limitations of its environment.
`
public void pushBestEffortsData(String name, Object data);
`

**Comment by mathieucarbou** [comment]
It's ok for us, we'll adapt.

I guess your idea is to pass a sort of "category" right ? Not a name ?

As I said, we just NEED this method to be there asap (because we have currently 3 issues waiting for it). 

So whether it's a String, an array or something else, we'll adapt and make our code working consequently, without also any returned data :-) So we have an agreement and even if you want to change the signature further, go for it: we just need it and we will adapt consequently.

My only concern with a name is that there is no way to cleanup the underlying buffer. As I explained, we need to implement it as one ring buffer per category. Because notifications, stats and op. events have different frequency, number of data, etc. And the idea behind a path[] is that I wanted to store the ring buffer in the tree so that it can be created / cleaned-up if a parent node is create / cleaned-up.

So if we go with that method, there will be 1 ring buffer per category, which will leak. Except if we have a sort of `destroy(category)` method perhaps.

Anyway, we will provide our own `IMonitoringProducer` interface for extensions / easy of use, and we will rely on it as possible (when lib depends also on the consumer), and we will delegate to the real `IMonitoringProducer` behind. Here what we will do is probably find a way to store the ring buffers into the tree, in the appropriate root, depending on a string pattern such as a/b/c or something else if there is no way to cleanup the buffers when not used anymore by the producer.

Another way would be to make `IMonitoringProducer` extend `Closeable`, like we did for the consumer. This would allow us to separate the ring buffers from the tree and be able to clean them once they are read and once the producer is closed.

Do you have an ETA for the PR ?

Thanks!

**Comment by mathieucarbou** [comment]
UPDATE: After thinking, a close() method won't work... Because there will be several producers for the same path. That's why a tree structure helped here. Because in the opposite of the addNode / removeNode where the producer is responsible to create the paths, in teh case of one consumer and multiple producers, which we have now, it is up to the consumer to create the paths.

In our case, this is the responsability of the management entity, for its root nodes, and then several producers could push(path, data) and if the underlying node is available, then the data will be put in the structure behind. And once the management entity is gone, all its ring buffers are gone also. Because no more consumers.

addNode / removeNode works fine when there is one producer and multiple consumers.

But now we need multiple producers and 1 consumer, which control the lifecycle of its underlying buffer.

**Comment by jd0-sag** [comment]
The life-cycle of the underlying buffer shouldn't have explicit control within the producer since it is up to the implementation and the consumer, how the information is used.  Given that it is low-fidelity, those buffers can be removed at any point:  either because they were drained by the consumer or because there are too many of them or they are too full.  I am still not convinced that you will need all that many of these or that they can't still be managed in one buffer (or just store the "one latest element" for each name).

Also, if your lib that is used by the other entities requires both a producer and a consumer side, that implies that this is wrong (nothing prevents it from being used that way, it just doesn't make sense).  The consumer interface of the service should only be used by the monitoring entity "consuming" the data.

This may become a bigger issue when we investigate how the passive-side of this needs to work (since a consumer interface is pretty well guaranteed not to work in that environment).  We still need to figure out the details, though, and how a platform-provided interface shim will coexist with your user-defined one (since that is currently a hole in the broader service design - or just something we need to approach differently).

**Comment by mathieucarbou** [comment]
Yes, agree. It would then work like this:

1. Call to `ReadOnlyBuffer iMonitoringConsumer.getOrCreateBuffer(String category)` to create the buffer from the consumer side

2. Producers can call `public void pushBestEffortsData(String category, Object data);`  at any time, whether there is or not a buffer setup for this category

3. Consumer can call `Buffer.read()`, `Buffer.isEmpty()`, `Buffer.stream()` etc. (any read-only methods)
