### ISSUE TITLE
Interaction between services

### ISSUE THREAD

**Issue by AbfrmBlr** [Terracotta-OSS/terracotta-apis#138]
While developing state service, there was a need for services to interact among themselves. As of now, there is nothing in api which allows this. But it can be done by passing the `ServiceRegistry` reference at the entity level to the services using the `ServiceConfiguration`. As of now this works, since the api is not explicit about the interaction, will trying to get service using the service registry passed on to the entities be a problem. Or do we need an explicit boundaries defined about service registry usage.

**Comment by jd0-sag** [comment]
This is an interesting approach and it should probably be safe since it isn't creating a new `consumerID` for the service to use another service, as it is using the same `ServiceRegistry`.  In that sense, this is little different from making the service requests, in the entity level, and passing specific offerings of one service into another (via either its `ServiceConfiguration` or its public interface).

We probably just need to formally document some of the things that must be kept in mind when approaching it this way (I will write them here in case someone realizes that this list is invalid/incomplete before we find somewhere to put the doc):

- services are still going to be loaded in their own class loaders.  This shouldn't be a big concern so long as one service is only using another the same way an entity does (since entities would see the same isolation)
- while each call to `getService()` returns a unique instance, they still share the same backing state (subject to how the backing `ServiceProvider` implements this).  While an entity must be aware of this when asking for the same service multiple times, a service must also not assume that it has any kind of isolated access to what the service provides
- while it is probably still preferable for the entity to carve up the provisions of one service between itself and various service(s) (so that it can impose its own sense of namespacing or isolation), passing the registry through the config is safe so long as the backing `ServiceProvider` doesn't _leak_ these between different `consumerID`s (which arguably would apply to anything externally pulled from one service and passed into another, anyway)
- the main concern we need to keep in mind is that the services are expected to act per-`consumerID` (effectively equivalent to per-`ServiceRegistry`) and that the entity must realize this when exposing its own `ServiceRegistry`
