### ISSUE TITLE
Expose consumderID of an entity via its PlatformEntity in the monitoring tree

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-apis#140]
From server entities, we need to expose management information in the voltron tree, under a specific root. 

I.e.: something like this:

```
management / entities / entityType / entityName /  capabilities
management / entities / entityType / entityName / contextContainer
```

This information would then be read by the TMS entity. So the idea here is that the server entity service needs to know enough information at the entity creation time (entity type and entity name) so that we can expose all the management information into a meaningful path.

On consumer side, the information we have is from 

```
platform / entities / ID (PlatformEntity)
```

`PlatformEntity` has the entity name and entity type.

So consumer-side we can access only:

- the ID
- the entity name
- the entity type

So we would need access to all these information in the entity server service so that we can expose in the tree by using this information.

Or, having another way to do the linking...

This issue currently is needed and blocks us from completing our current work for:

- Terracotta-OSS/terracotta-platform#127
- ehcache/ehcache3#1008

**Comment by jd0-sag** [comment]
Our current thinking includes a few points:

* we will add consumerID to the PlatformEntity, in the tree
* we recommend that the monitoring service implementation focus on a less literal global tree structure, instead interpreting the calls from entities as a forest:  each tree rooted at the corresponding entity's consumerID (logically, at least) with the knowledge that consumerID 0 is special to the point where entity node removal can be used to purge the per-entity roots

**Comment by jd0-sag** [comment]
My only immediate concern, with respect to this different interpretation of the tree, is that it will need to be rationalized when we start pushing passive trees to the active.  I don't think that is a hard problem, on any technical level, just on the level of how to define how it will be expressed, potentially relying on a convention (for which there is precedent:  the shape of the platform tree is already defined in the API and this would be similar).

**Comment by jd0-sag** [comment]
To flesh this out in greater detail:

The key is realizing that the IMonitoringProducer implementation need not literally interpret the API as a single tree.  That is really just to allow balanced data create/destroy events in a finite space (the tree further allowed data to have a "logical location", to create a sort of logical namespacing of the data - otherwise, it would just be create/destroy with a key name).

This also assumes that we add `consumerID` to `PlatformEntity`, which we will do as soon as we get buy-in on this.

consumerID 0 (the platform) creates the entity for consumerID 1 (a new, user-created entity) by calling addNode:  `/platform/entities/<something>`.  This PlatformEntity has consumerID 1.

The IMonitoringProducer implementation, however, re-parents this as a local-global mapping (each consumerID being a tree in a forest) with the form:  `/0/platform/entities/<something>` (for example - it could reshape this further or not even use a tree, arguably - depends on how deeply it wants to interpret the constant paths defined in the interface)

consumerID 1 then calls IMonitoringProducer to register some data about itself using addNode:  `/monitoring_data/<something>`.

As before, the IMonitoringProducer implementation re-parents this to `/1/monitoring_data/<something>`

At this point, the TMS is able to use its richer reading interface to ask for the information describing the entities on the server.  One of them is the instance with consumerID 1 (which is found in the list of PlatformEntity instances).

From here, the TMS knows where to find the data associated with the entity.

Additionally, when the TMS sees the removal of PlatformEntity instances, it can purge that single tree, no matter its internal organization.  This would tie together the entity life-cycle with any data it provided, without the entity needing to hard-code the shape of the tree as only the monitoring service would now need to know what "special" meaning exists within that branch.

Arguably, this means that even the top-level `platform` branch is now redundant since that is ALWAYS defined as being the data under consumerID 0.

**Comment by jd0-sag** [comment]
In light of some conversations abut this, here are some points and key questions to keep in mind:

- The only API change this entails is adding the `consumerID` to `PlatformEntity`
- The main question underlying the rest of this issue is whether or not we think it makes sense to change the tree from a global concept to a virtualized, per-entity concept
- The second question, assuming we do think that the change is a good idea, is how the service should internally manage these per-entity trees.  Are they, for example, independent roots in a forest (as described above) or do we directly parent them under the nodes the platform creates for its PlatformEntity instances?  This is largely an implementation detail, though

Another point realized through some further discussion and investigation is that this requires that the order of events regarding when the PlatformEntity is added to the tree be more concretely defined.  Currently, the implementation adds the node _after_ the entity has been instantiated.  However, this would be incompatible with this design as there would be no way to connect any information added to the tree, during entity creation, with the entity, at that time, since the service had not yet been told about the PlatformEntity with that consumerID.

This means that the PlatformEntity will need to be added to the tree before the entity, itself, is created (which also means that an unexpected failure in creation will need to explicitly remove this new node).
