### ISSUE TITLE
ServerEntity API use of ConcurrencyStrategy UNIVERSAL_KEY

### ISSUE THREAD

**Issue by ChrisGreenaway** [Terracotta-OSS/terracotta-apis#145]
Please add:
1) a ConcurrencyStrategy that returns UNIVERSAL_KEY for all messages (in the same vein as NoConcurrencyStrategy)
2) documentation to ConcurrencyStrategy.getKeysForSynchronization() to explain what set of keys should be used when concurrencyKey can return UNIVERSAL_KEY or MANAGEMENT_KEY.

**Comment by jd0-sag** [comment]
While (2) is definitely a gap in the current documentation which we need to plug (especially considering how it is one of the more complex parts of the system), (1) is probably not something which can reasonably be added.

There are 2 reasons for this:

1. It is unlikely to be useful.  `NoConcurrencyStrategy` was added since we found it was what most entities wanted to use, or at least in their first version.  Beyond that case, I am not sure where someone would want to generally use a "run everything concurrently all the time with no logical constraints"
1. It wouldn't work with passive sync.  The concurrency strategy allows the entity to communicate its logical organization to the platform for both purposes of invoke scheduling but also how data can be synchronized to a passive.  This is because synchronization is done on a per-key basis, via `getKeysForSynchronization()`, and that would be an unbounded set if the `UNIVERSAL_KEY` were used for _all_ messages.
