### ISSUE TITLE
Better javadoc on ServiceProvider.clear()

### ISSUE THREAD

**Issue by ChrisGreenaway** [Terracotta-OSS/terracotta-apis#153]
There's a long javadoc comment on this method already, but I struggled to see how this method fits into the lifecycle. When is clear called in relation to initialize()? I presume that clear() is never called before initialize() and that initialize() will not be called again until clear() has been called and that every time initialize() is called, clear will ultimately be called. Are these statements true? I assume these things, because I want to use clear() to release resources held by the ServiceProvider. If they are not true, then how do resources get released?

**Comment by jd0-sag** [comment]
This is an odd one so we can add some more information around the circumstances of this call.

The short answer is that it usually _isn't_ called since the ServiceProvider lives as long as the server, which uses a "crash only" model, never relying on clean shutdown.  The case where this is called is when the server receives a zap.
