### ISSUE TITLE
Proposals for IStripeMonitoring improvements

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-apis#156]
This ticket is an open discussion regarding some improvements we would like to be made regarding the `IStripeMonitoring` interface.

Currently, the monitoring service is using its own [`IStripeMonitoring`](https://github.com/mathieucarbou/terracotta-platform/tree/issue-147/management/monitoring-service/src/main/java/org/terracotta/management/service/monitoring/platform) interface, reflecting our needs, and when the platform request the `org.terracotta.monitoring.IStripeMonitoring`, an adapter class is used to bridged the 2 interfaces.

So what would be interesting I guess for the Voltron team is to see:

- [what we would expect to have at the moment, regarding our needs](https://github.com/mathieucarbou/terracotta-platform/blob/issue-147/management/monitoring-service/src/main/java/org/terracotta/management/service/monitoring/platform/IStripeMonitoring.java)
- [what we have at the moment](https://github.com/Terracotta-OSS/terracotta-apis/blob/master/standard-cluster-services/src/main/java/org/terracotta/monitoring/IStripeMonitoring.java)
- [How we adapt one to the other](https://github.com/mathieucarbou/terracotta-platform/blob/issue-147/management/monitoring-service/src/main/java/org/terracotta/management/service/monitoring/platform/IStripeMonitoringAdapter.java)

Here are a list of proposed changes:

__Additions__

- [ ] ➕  `void serverEntityCreated(PlatformServer sender, PlatformEntity entity);`
- [ ] ➕  `void serverEntityDestroyed(PlatformServer sender, PlatformEntity entity);`
- [ ] ➕  `void serverStateChanged(PlatformServer sender, ServerState state);`
- [ ] ➕  `void clientConnected(PlatformConnectedClient client);`
- [ ] ➕  `void clientDisconnected(PlatformConnectedClient client);`
- [ ] ➕  `void clientFetch(PlatformConnectedClient client, PlatformEntity entity, ClientDescriptor clientDescriptor);`
- [ ] ➕  `void clientUnfetch(PlatformConnectedClient client, PlatformEntity entity, ClientDescriptor clientDescriptor);`
- [ ] ➕  `void setState(PlatformServer sender, String[] parents, Serializable value)`

__Removals__ _(or moved to a more specialized interface for passive-to-active com.)_

- [ ] ➖  `boolean addNode(PlatformServer sender, String[] parents, String name, Serializable value)`
- [ ] ➖  `boolean removeNode(PlatformServer sender, String[] parents, String name);`

__Details__

1. I think it would be nice to separate platform calls from passive to active communication: so that the platform no more calls `addNode` and `removeNode` for platform events
2. `addNode`, `removeNode`, `pushBestEffortsData` are NEVER called by M&M currently (no need)
3. consumers of the monitoring service (entities) are using the [`MonitoringService`](https://github.com/mathieucarbou/terracotta-platform/blob/issue-147/management/monitoring-service/src/main/java/org/terracotta/management/service/monitoring/MonitoringService.java) interface, which represents high-level calls that are M&M-related. If you are interested into seeing how M&M works and what are our needs, this is where to look :-)
4. Although we do not have any use case to implement now, we know that in the future, we will need to receive notifications, stats and expose some states from the passive. So a communication layer will be required, BUT in the passive, consuming entities will still use the `MonitoringService` interface. So what we will need is to send from passives to active the calls made on this interface (for some calls). So it means that on a passive server, we would probably have a different implementation of the `MonitoringService`, that delegates to a communication layer perhaps ?
5. The communication layer from passives to active could be extracted in a specialized interface other than `IStripeMonitoring`, because the communication layer will only be a service requested from the passive entities. 
6. In the latest discussions, we did not see any use case where topology information and M&M states (registry, capabilities, tags, etc) have to be "replicated" on passives, since they are all data that can be resent on reconnection, or rebuilt.
7. If we keep `addNode`, `removeNode` and `pushBestEffortsData` for the communication layer from passives to active, I think it might work (__but like I said, we cannot ensure that since we have no use case to implement__)

Let us know what you think and if we need to talk about these items to see whether they make sense also to you ?

**Comment by jd0-sag** [comment]
The reason why we created `IStripeMonitoring` is literally to address the issues of passive-to-active communication so changing this to move away from that goal is counter-productive.

The reason why these calls go through such a generic interface is because the platform is only meant to be one consumer of the interface (among any other passive-to-active requirements), not a specialized interface for platform-specific data.

**Comment by mathieucarbou** [comment]
ok so it means the "communication layer" will be the same as the interface from where we receive platform events. For us, these are 2 different concepts, but if they are in the same interface because it is easier for you, ok then ;-)

And what about the proposal of adding new method calls ?

**Comment by jd0-sag** [comment]
We try not to describe where the communication layer is since it causes increased specialization in the senders and receivers, effectively growing the contract required to use the system and requiring a more specific and rigid implementation of the platform.

The idea is that `IMonitoringProducer` is what a producer of monitoring data (platform or other entities) uses to **send** this data to the monitoring implementation.  `IStripeMonitoring` is what is used by a monitoring implementation to **receive** this data.  The requirement that the data be `Serializable` means that it will work the same way whether or not there is a network communication layer or just a method call in between.

It means that the same implementation could make sense of data coming from any number of sources on the axes of both entities and servers, without any specialization of any case (it just needs to know what the node path is for any data it wants to interpret in any more meaningful way - the contract between the entity and the monitoring service - everything still works even if this is incomplete).

The main reason why I don't want to add these methods is that it would require a redundant implementation of some kind of tree listener, within the platform, only to grow the size of the interface.  Ideally, a monitoring implementation could receive any data like this and only interpret it if it cares to provide some specific functionality around it.  This is exactly what it would need to do for receiving any other monitoring data.

Hence the reason for the current interface:  it allows that kind of arbitrary flexibility without further specialization of the caller or implementation.

**Comment by mathieucarbou** [comment]
But why you have extracted `serverDidJoinStripe` and `serverDidLeaveStripe` from `addNode` and `removeNode`, and why we would not do the same for `serverEntityCreated` and `serverEntityDestroyed` ? 

I don't understand (__from a user perspective__) what is the difference between both, and why you could extract one and not the others ?

**Comment by mathieucarbou** [comment]
(sorry - clicked on the wrong button)

**Comment by jd0-sag** [comment]
Those weren't extracted from addNode/removeNode:  they were introduced to give a lifecycle to the PlatformServer objects which are used to provide context to the data coming into `IStripeMonitoring`.  This just tells you what those mean so you can distinguish between data coming from different servers.
