### ISSUE TITLE
Task scheduling and async task execution support

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-apis#158]
For stat computation to work, we need from a server entity to be able to pass a `ScheduledExecutorService` to the stat library.

Since Voltron does not allow to spawn threads, we need a way to support scheduling in Voltron so that we can provide an adapted implementation of a ScheduledExecutorService to this stat library.

Tasks registered in it would have their execution triggered thanks to a platform callback somewhere at a specified interval.

**Comment by mathieucarbou** [comment]
@anthonydahanne : FYI

**Comment by mathieucarbou** [comment]
Adding reference to ehcache/ehcache3#1573

**Comment by jd0-sag** [comment]
Trying to figure out if we need this to be a distinct service or just make this another few methods within `IEntityMessenger` (since those already "message self" - we really just want a "message self after time" and "message self at periodic interval").

The implementation will be the tricky part but figuring out how this will appear, to the entities, is worth some discussion.

**Comment by jd0-sag** [comment]
In terms of what I am prototyping, I have added these 3 methods to `IEntityMessenger`:

`Object messageSelfAfterDelay(EntityMessage message, long millisBeforeSend) throws MessageCodecException;`

`Object messageSelfPeriodically(EntityMessage message, long millisBetweenSends) throws MessageCodecException;`

`void cancelTimedMessage(Object token);`

(I will probably create an opaque interface type to use as this token - `Object` is vague)

Some extra concerns I need to make sure are covered are that all messages registered for an entity are implicitly cancelled in these circumstances:

- the entity is destroyed
- the server fails-over from passive to active
- the server is restarted

**Comment by mathieucarbou** [comment]
ok!

@jd0-sag : correct me if I am wrong, but with this mechanism, we could then create a jar file the contains both a voltron server and a server entity, the server entity being responsible to call itself and the voltron service then providing a jdk's scheduled executor service intreface, that would be backed by the self-calls made by the server entity in its own jar ?

I am thinking about how to use it and if we do not abstract a bit more this concept into another voltron service, eventually backed by another server entity that schedules itself, I fear that all the boilerplate code would need to be within the ehcache entity, within the tc db entity, just to be able to schedule M&M stats, which seems wrong to me.

Perhaps to simplify the use of this api, then having a sort of voltron-scheduler.jar that contains a service provider and a server entity (that won't receive clients but will do some scheduling) would help the users.

**Comment by jd0-sag** [comment]
This item is purely to deal with creating the service that allows the delayed invocation to be requested.  That translates into a message being sent down the invoke path either after a delay or periodically.  Any higher-level mechanism required should be something which can be built on top of that, but it is unrelated to this item.

I am not sure what these packaging concerns are about.  This interface will be a standard-cluster-service, its implementation provided by the server.

**Comment by jd0-sag** [comment]
While this is generally working, my biggest question is now surrounding the visibility of the message being periodically sent.

Initially, I was thinking that it should be local server only (it can be requested on any server, active or passive, but will never be replicated) but some concerns have me questioning if it might make more sense for this to be active-only and replicated:

1. active-only would be consistent with the other methods in `IEntityMessenger`.  If we wanted substantially different semantics, we would need a totally different service interface (not a problem, just sort of unfortunate since they seem otherwise very similar)
1. local-only would create a completely distinct message pipe, only used for this purpose.  While possible, this does create some very specialized code-paths which it would be preferable to avoid (although this is a week argument)
1. local-only would allow the passive to independently "drive itself" which we have largely tried to avoid since it makes stripe inconsistency bugs that much easier to create
1. local-only would remove the ability for the user to leverage the new `ExecutionStrategy` to determine where timer messages go, from the active
1. active-only would remove the special-case of implicit message cancellation on fail-over

Still not sure, though, since the use-case is a primarily local-only one for internal timer/background operations.  In that case, it _does_ make sense for these messages to be local-only.  In that case, replicating a timer interrupt seems somewhat odd (yet, at the same time, completely consistent and correct).

**Comment by jd0-sag** [comment]
Continuing to think through this, I am trying to keep in mind the goal of needing to support a `ScheduledExecutorService` implementation.

These are the 3 options:

1. Add to `IEntityMessenger`.  This would make the request active-only and replicated.  The current prototype uses this.  This is probably not sufficient since it means that the passive would be incapable of implementing `ScheduledExecutorService`, even though it would maintain the existing rule that all decisions are made by the active.
1. Create a new service interface which operates similarly to `IEntityMessenger` but is available on both active and passive and NEVER replicates messages (they would pass through `ConcurrencyStrategy` but not `ExecutionStrategy`).  While breaking the normal "passives don't make active decisions" rule, it would cleanly support `ScheduledExecutorService` on any server.
1. Create a new service which exposes something akin to `ScheduledExecutorService`, directly.  This probably isn't a good option as it breaks not only the rule that passives shouldn't make decisions but also removes the ability to consistently control execution of entity code through the `ConcurrencyStrategy`.  It is still worth keeping on the table, however, since it is a way of looking at the problem.

Overall, this points out an interesting problem:  the needs of `ScheduledExecutorService` on the passive are incompatible with a purely active-passive design.  The approaches (1) and (2), above, demonstrate the most similar ways of addressing this dilemma by sacrificing one requirement or the other.

(2) is probably what we ultimately need unless we can figure out a way of rationalizing all the special-cases in both implementation and design incurred by (3).

**Comment by mathieucarbou** [comment]
I agree, 2 seems better because we don't need replication and we need to have this scheduler available on both active and passive. 
Also, the scheduler will be used to compute stat samples, which is a time sensitive thing. So we have to keep in mind to reduce the overhead to "simulate" a `ScheduledExecutorService`.

**Comment by jd0-sag** [comment]
After some conversation with @mathieucarbou, it sounds like their specific case is better handled by moving their logic to the service layer (since services don't need to concern themselves with entity lifecycle or active/passive state).

We will proceed with this change, however, since we have some other future consumers.  This also means that we will proceed with solution (1) since it gives us what we want in a consistent way without violating any of the existing constraints on passive responsibilities or entity execution entry-points.
