### ISSUE TITLE
Add a Connection.closeHasBeenRequested() to know when a client has requested a connection to close

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-apis#210]
I am opening an issue to discuss how we could get the state of a connection. Here are some use cases / problems we encountered so far:

1. When a connection is opened, it can only be closed. We cannot tell whether the connection is really physically connected to a server and working.

2. When implementing the `ClusterManager` for Vertx, we need at some point to be able to check through something like `Connection.isConnected()` whether we can really send some messages or not. Vertx is not design to allow some blocking operations to be performed (i.e. when closing) and we have to check whether the connection is opened or not first before it tries to send some messages. 

I think it was @henri-tremblay 's idea behind https://github.com/Terracotta-OSS/terracotta-core/pull/518

3. In management, currently, we are doing all our voltron invocation using futures and timeout. __This is not what we want__, but this is the ONLY WAY we have currently to __detect when there is a disconnect and reconnect__, because an operation times out, then, succeeds again. This is wrong, because an operation timeout could also mean that the server is really working, but just slow, or a failover takes a long time. But we have no way to tell the difference between a real timeout on an operation (i.e. slow), and the connection that is physically disconnected. We need to report a disconnect event to the UI, but also switch to the diagnostic  / recovery service, ONLY if a connection is broken, not in the case where the operations times out because server is slow or in a failover.

4. For specific use cases such as being able to switch to a diagnostic entity or recovery use cases, we first need to know that there has been an issue with a connection. And we cannot tell currently that a connection has been physically disconnected because the server is down.

Since a connection is able to failover, it supposedly knows about the other nodes. So I don't know for this specific point what to report (because some passive might never come up ACTIVE). So perhaps the solution would be to report states `Connection.getState()` like `CONNECTED`, `WAITING_ACTIVE`, `DISCONNECTED`, etc.

So this request is both related to the work we need to do in M&N this year and also relative to the issues we encountered when bridging Vertx with the Terracotta Server. 

CC @anthonydahanne @GaryWKeim @henri-tremblay @ljacomet

**Comment by GaryWKeim** [comment]
Absolutely needed.

**Comment by jd0-sag** [comment]
There are a few issues with this.

- Are you interested in knowing whether you already closed the connection (which you should know from within your own code) or whether it has been disconnected at the socket layer?  If the latter, you typically only know that when it is too late (the connection has been effectively gone, for a while, but there was no explicit disconnect - happens in the case of anything but a clean remote-side disconnect)
- Even if you could ask if the connection is still up, that can asynchronously change underneath you at any point, so it wouldn't really protect you
- The state transition of the connection, during a fail-over, is also happening asynchronously of the thread which is running the client code.  If you ask twice and see it is connected, in both cases, that doesn't mean that the physical connection is to the same server
- Any connection which represents an abstraction over potentially more than one stripe connection wouldn't be able to sensibly answer this since it could be "partially" connected

In all of these cases, you can't mitigate the need to handle this as a timeout, at a higher level.

The best that could be done, is a notification that these changes had happened, but that doesn't tell you if what you are about to do will be non-blocking (just that something interesting happened in the past).  Even that would be potentially problematic in the case of any sort of aggregate connection.

I am more interested in understanding the specific problem that you have and looking at from the top, first.  I am not convinced that this kind of feature would solve your problem, given the above-mentioned reasons.

**Comment by mathieucarbou** [comment]
As I explained, we need a way to make the difference between an invoke that times out (but can still be executed on server because server is slow or else), and when the connection is broken, before we send any invoke that will or not timeout (and thus block).

**Comment by jd0-sag** [comment]
> when the connection is broken, **before** we send any invoke

But the connection can drop at any point.  Asking if it is up "now" (assuming that such a thing can reliably be determined) doesn't mean that it will be up later.  This would only solve the trivial cases but you would still need the same machinery to handle all the other cases.

If this were more about being able to somehow interpret a timeout (after it happened), I could almost see the point (not quite, though, since the disconnect may have happened after the server received the message - it would still run it), but it doesn't sound like that is the problem you are trying to solve.

**Comment by mathieucarbou** [comment]
1. So what if all servers go down and no passive become active ? How we can tell that the Connection is "broken" ?  By broken I mean that an invokation call with a timeout will timeout but we don't know why, and an invokation that is blocking will block indefinitely.

2. We still need to have a sort of `Connection.isClosed()` when the connection is shutdown or closed because in a lot of framework (vertx is one, ehcache is another one), the TC Connection might be provided by an external service. So another service using it might request to know the state of this connection in case it is closed externally. So it's not true that I will know when the connection is closed.

**Comment by anthonydahanne** [comment]
having a isDisconnected() method would allow us to make better decisions when (before or after) a timeout occurs (true ? don't try retry immediately and notify the user or system somehow otherwise keep on trying, it was just slow)

**Comment by myronkscott** [comment]
Mathieu.  That inferring too much about the underlying implementation than we should expose.

**Comment by jd0-sag** [comment]
After our discussion, I think we managed to distill this down to a very specific request:

Expose something like `wasShutDownLocally()`, on the `Connection`, which can only tell you if someone called `close()` on this object instance.  **It doesn't tell you anything about the state of the network, just the state of the object instance.**

The question now comes down to whether or not the `Connection` is the right place for this or if the use-case is too specific to one situation to justify pushing it into the API.

One core agreement we do appear to have is realizing that you could not use this to infer whether a message you are "about to" send would be able to go over the network since another thread can close the connection, within the object, at any time, and the network can fail asynchronously, at any time.  Catching the exception for the closed connection is always required, when sending a message.

**Comment by myronkscott** [comment]
The more I think about this, the more I question the usefulness of such a flag.  Part of the problem here is that state of the Connection doesn't really tie directly to the state of the associated client-side entities.  If the client side entity calls ```wasShutdownLocally()``` and true is returned, it is still possible for an associated entity to have incoming messages processed and endpoint callbacks being called.  I'm more in favor of having any shutdown being tracked and reported by the client side entity or the client side application.

**Comment by mathieucarbou** [comment]
yes @myronkscott , agree! The only reason of this flag is that we can have a way to know that `connection.close()` has been called, potentially from an external place that we do not control, so that we can act on this fact. That's the only reason.

**Comment by ljacomet** [comment]
Maybe this needs one more discussion, but from what I read it feels like the ability to register listeners on a connection would be a better approach. These could get called when the connection is knowingly closed (whether from the local or remote end). Wdyt?

**Comment by myronkscott** [comment]
```EntityClientEndpoint``` already gets notified when a connection is closed before associated entities with ```EntityClientEndpoint.didCloseUnexpectedly()```.  I think part of the problem here is that we are equating a closed connection state with apis that are one or two levels removed in ```EntityRef``` and ```EntityClientEndpoint```.  I don't think we want to directly associate closed state of the connection with state of the entity.  They are mostly the same but not completely.  I guess we can add external listeners that get notified at the same time as ```EntityClientEndpoint.didCloseUnexpectedly()``` but is it really necessary?

**Comment by myronkscott** [comment]
correction.  The correct method is ```EndpointDelegate.didDisconnectUnexpectedly()```.  Requester will use this callback
