### ISSUE TITLE
Ability to enumerate entities.

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/terracotta-apis#213]
In order to support enumerating the datasets within a server I will need some way to enumerate the known entities (in principle only of a single type) within a server.  I presume that something like this is getting exposed through a monitoring interface somewhere... I just need the same information available through a regular voltron connection.

**Comment by jd0-sag** [comment]
Is this not something which can be done through some kind of indexing entity?  Otherwise, you don't really have a way to implement protection around datasets coming in/out of existence, asynchronously to your call.  Additionally, it would require that all datasets have a static global namespace (which might be sufficient, for now, but I suspect that won't hold up, in the long run).

**Comment by chrisdennis** [comment]
Sure it could be exposed through an indexing entity... and how does it get that knowledge.  Given that through a connection right now you can fetch entities it doesn't seem too much a stretch to have the connection be able to tell you what entities can be fetched.

Abstracting this through an indexing entity doesn't change anything about datasets coming in to or out of existence.  As regards a single global namespace thats already the case.  An entity name as I understand it is composed of a string and it's type... that combination must be unique.

**Comment by jd0-sag** [comment]
I am thinking more about indexing and namespacing along the lines of how things like EhCache manage caches under a cache manager and mediate the create/destroy through an interlock there (as I understand it).  The application's resource namespace, as opposed to "entity instance namespace".

Mostly, I am trying to figure out how this would be used (reliably, as well) since I would have assumed that the entity is connecting to something specific (not sure how it decides what it is doing, otherwise).

I don't want to create something which turns out to be gratuitous and unusable due to race conditions and a lack of ability to "discover" the logical intent of an entity, given only a list of server-side resources.

**Comment by chrisdennis** [comment]
I don't desire to create any contract whereby requesting the list of things that exist at time x implies anything about the existence of things at time x+∂.  I want the equivalent of `SHOW DATABASES` or perhaps `SHOW TABLES`. I don't expect this to be a very dynamic set of things and if it is I expect the user to understand that and compensate.  Given that Voltron must know what entities exist of what types it seems that it would be simpler for TC Store to just ask Voltron than for it to have to maintain a parallel structure with no real method of validating that the two structures are drifting.  I want to know precisely "what exists" not "what I think exists".

**Comment by jd0-sag** [comment]
It is more about just making sure that the answer Voltron would provide is actually something which can be used to solve a problem.  The question isn't really the difficulty of implementation, just making sure we continue to support something which is actually used.

Details of how to implement it can be discussed:

- is this a top-level connection API method?
- does this use a preexisting monitoring entity (since it already has that data)?
- do we define some other kind of "standard entity" which can answer higher-level questions like this?
- (something else...)

**Comment by myronkscott** [comment]
I believe this has been handled a different way.  Please reopen if not the case.
