### ISSUE TITLE
Add overloaded addState methods to StateDumpCollector

### ISSUE THREAD

**Issue by ChrisGreenaway** [Terracotta-OSS/terracotta-apis#240]
StateDumpCollector would benefit from having overloaded addState methods such as:
  addState(String key, int value)

Otherwise there is lots of code such as:
  addState("state", String.valueOf(state))

We should accept primitive value objects and possibly Object too.

**Comment by mathieucarbou** [comment]
I need this too.

**Comment by myronkscott** [comment]
Use the JSON string key?

**Comment by mathieucarbou** [comment]
No because there is no real json support. 

To have a real json support with this current API, users of the state dumpable interface should depend on json libraries like jsr 353 (better, at least this is a common api) and/or jackson. So it would mean that each entity or service we want to dump would need to add its own json layer to correctly log what we need to log. This does not make sense to me and could create classpath issue the way voltron isolate things and put some in a common classloader.

And it is not true that it is safe to manually construct json strings because of the many escaping rules that would require to write some common classes.

I would do in JSON (and I would love) but for that, the API should support at least a JsonObject or Json type from JSR 353 and voltron should provide a default implementation for the javax.json api on its classpath.

This would be awesome to have that.

**Comment by ChrisGreenaway** [comment]
I agree with Mathieu, in terms of what would be required to generate JSON.

Not bothered about JsonObject / type in our API.

**Comment by myronkscott** [comment]
I think you guys are mis-understanding what I am saying.  There is nothing preventing you from pulling the dependency on your own and generating the the JSON output in a proper JSON string then installing it in the state dump through the JSON key.  What the platform then does with that string can be determined later.  What I want to avoid is overloading the state dump API with a bunch of structures for everyone's flavor of the week.

**Comment by ChrisGreenaway** [comment]
I absolutely understand your proposal, but I don't like it. I don't like that you have to pull in JSON libraries and generate JSON strings on the calling side of the API.

I also don't think that we will add a "bunch of structures for everyone's flavor of the week" - we just need an array/iteration type thing (Mathieu suggested a reasonable API in our earlier discussions).

With that addition, we would then have enough power to represent any object state. After all, that's all JSON has: key->value, sub-state and arrays. We are just missing the array part.

**Comment by myronkscott** [comment]
The issue is having a standard format and what should be supported in this API.  My thought is that this API should be very thin without much specification.  I do not believe that we should support a rich format directly with primitive types, null value specification, ordering concerns, array types, object types, etc.  I am not being a proponent of JSON but rather a simple, nested string representation and nothing more.  If you want a richer API, we will provide that with implementation as a library

**Comment by myronkscott** [comment]
We do not want to re-invent the wheel.  This type of [API](https://fasterxml.github.io/jackson-databind/javadoc/2.5/com/fasterxml/jackson/databind/node/ObjectNode.html) should provide all the richness desired from an object building API.  Output to JSON string makes it easy for the platform to consume.  We will provide an implementation module that make it easy for entity and service implementors to use this interface.

**Comment by myronkscott** [comment]
addState now takes objects and at a minimum will support lists and maps
