### ISSUE TITLE
New methods on PlatformService

### ISSUE THREAD

**Issue by esebasti** [Terracotta-OSS/terracotta-apis#303]
Provide following methods on PlatformService

1) Overloaded stopPlatform() to stop server with non-zero exit code
2) upTime() as elapsed time since TCServer.getStartTime()

**Comment by myronkscott** [comment]
I think we should add the stop time but not exit codes.  Exit codes should be internal to the platform.  The problem is that certain exit codes mean very specific things.  If we expose this to stopPlatform(), we will need to filter out specific codes.  I'd rather just stop the server without codes.  I don't think we need exit codes for what you are working on, do we?

**Comment by esebasti** [comment]
I understand the risk but non-zero exit code is needed for shutdown triggered by any error. How about exposing a method to exit with a generic code?

**Comment by myronkscott** [comment]
I will add a fatalError method with description.
