### ISSUE TITLE
MessageCodec marshall/unmarshall methods should throw a checked exception

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/terracotta-apis#35]
It would seem to make sense for a MessageCodec implementation to required to throw a specific checked exception type when presented with incorrect input.  What happens at the moment if I throw a runtime exception from a deserialize/serialize method?

**Comment by jd0-sag** [comment]
I looked at what we would need to do to add an exception for this case to the existing EntityException hierarchy and it probably isn't appropriate to do so (since those exceptions are really meant to be thrown _by_ the platform, not the user code).

The requirement of needing a specific deserialization exception is obviously a good one, though.  I will prototype a new exception, unrelated to our other types, in the same package as MessageCodec.  I just need to test this and make sure that the rest of the platform does something reasonable when there is an exception thrown at this point.

My thinking is "MessageDeserializationException" as a checked exception, thrown by both deserialization methods, and we will also wrap these calls with checks for RuntimeExceptions which we can internally wrap in one of these if they are thrown.

**Comment by jd0-sag** [comment]
I have a prototype of this MessageDeserializationException which I am testing now.  I didn't originally create one for the "serialization" case since the message type is provided by the implementation but, after thinking through this, there could be cases where they construct an EntityResponse instance, of their own type, which is internally inconsistent, due to a bug elsewhere in their implementation, so it should probably be able to throw something, as well.

I will generalize this into "MessageCodecException" so that a checked failure can be thrown from any of the MessageCodec methods.
