### ISSUE TITLE
Create ConnectionService implementation for Passthrough

### ISSUE THREAD

**Issue by jd0-sag** [Terracotta-OSS/terracotta-apis#80]
Uses of the passthrough test environment are currently limited to the cases where the Connection object can be accessed, directly.  Many applications would rather operate on a URI since that is how a more general-purpose configuration is performed, etc.

Passthrough could be used to test these applications if we provided a URI scheme and corresponding ConnectionService.

**Comment by mathieucarbou** [comment]
That is mainly are use case in M&M, as I already explained you. 

So we had to develop a passthrough-extensions module which does exactly that, and also exposes the voltron ServiceProvider for the tests.

We basically ensure this ConnectionService comes first in the classpath, then we use a mock() construction that mocks the URI scheme we want by using the passthrough. We needed that because M&M supports several connection schemes.
