### ISSUE TITLE
PassthroughServer.stop() leaves internal PassthroughConnection thread running

### ISSUE THREAD

**Issue by cljohnso** [Terracotta-OSS/terracotta-apis#90]
When starting a `PassthroughServer`, an _internal_ `PassthroughConnection` is created (in `internalConnectPseudoConnection`) along with it's supporting thread (generically named "Client thread").   This thread is left running after a `PassthroughServer.stop()` is called.  Given there's no way to stop the thread external to `PassthroughServer`, this thread needs to be cleaned up during `stop`.

**Comment by jd0-sag** [comment]
I will change this so that the `ServerProcess` takes direct ownership of the `PassthroughConnection` created for the `PassthroughMessengerServiceProvider` since there appears to only ever be one of each and they are both created when the server is started or restarted so it should be straight-forward to life-cycle it along with the logical *server instance*.
